### ISSUE TITLE
code for Email not working

### ISSUE THREAD

**Issue by 99003521** [amanajaykalaskar/Mark_Analysis#4]
PS A:\..000LTTS\GENESIS\Mark_Analysis\3_Implementation\PythonCode>  python .\mail.py
Traceback (most recent call last):
  File "A:\..000LTTS\GENESIS\Mark_Analysis\3_Implementation\PythonCode\mail.py", line 3, in <module>
    s = smtplib.SMTP('sdlcgen@gmail.com', 587)
  File "A:\Python\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "A:\Python\lib\smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "A:\Python\lib\smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "A:\Python\lib\socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "A:\Python\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11003] getaddrinfo failed
PS A:\..000LTTS\GENESIS\Mark_Analysis\3_Implementation\PythonCode>

**Comment by 99003554** [comment]
@amanvkalaskar  the issue was resolved
